export const resturantList = [
  {
    type: "resturant",
    info: {
      id: "728301",
      name: "Burger King",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2024/6/11/a5cee281-c25f-494a-8cab-ba7f49acfb03_728301.JPG",
      locality: "New Palasia",
      areaName: "Indore",
      costForTwo: "₹350 for two",
      cuisines: ["Burgers", "American"],
      avgRating: 4.2,
      parentId: "166",
      avgRatingString: "4.2",
      totalRatingsString: "5K+",
      sla: {
        deliveryTime: 36,
        lastMileTravel: 6.1,
        serviceability: "SERVICEABLE",
        slaString: "35-40 mins",
        lastMileTravelString: "6.1 km",
        iconType: "ICON_TYPE_EMPTY",
      },
    },
  },
  {
    type: "resturant",
    info: {
      id: "69420",
      name: "Vijay Chaat House",
      cloudinaryImageId: "mstgatb2vu8v48kcua81",
      locality: "Nihalpura",
      areaName: "Rajwada",
      costForTwo: "₹150 for two",
      cuisines: ["Snacks", "Sweets", "Chaat", "Street Food"],
      avgRating: 4.7,
      parentId: "223165",
      avgRatingString: "4.7",
      totalRatingsString: "1K+",
      sla: {
        deliveryTime: 27,
        lastMileTravel: 2.3,
        serviceability: "SERVICEABLE",
        slaString: "25-30 mins",
        lastMileTravelString: "2.3 km",
        iconType: "ICON_TYPE_EMPTY",
      },
    },
  },
  {
    type: "resturant",
    info: {
      id: "84070",
      name: "Gurukripa Restaurant - Sarwate",
      cloudinaryImageId: "g5txnz35wlrgbskk3r8y",
      locality: "Sarwate",
      areaName: "South Tukoganj",
      costForTwo: "₹250 for two",
      cuisines: [
        "North Indian",
        "Thalis",
        "Indian",
        "Fast Food",
        "Chinese",
        "Beverages",
        "Desserts",
        "Jain",
        "Punjabi",
      ],
      avgRating: 4.4,
      veg: true,
      parentId: "92204",
      avgRatingString: "4.4",
      totalRatingsString: "10K+",
      sla: {
        deliveryTime: 30,
        lastMileTravel: 4.4,
        serviceability: "SERVICEABLE",
        slaString: "30-35 mins",
        lastMileTravelString: "4.4 km",
        iconType: "ICON_TYPE_EMPTY",
      },
    },
  },
  {
    type: "resturant",
    info: {
      id: "148404",
      name: "Om Namkeen",
      cloudinaryImageId: "okkh43ib3xm733hebgus",
      locality: "Jawahar Marg",
      areaName: "Lodhipura",
      costForTwo: "₹200 for two",
      cuisines: ["Snacks"],
      avgRating: 4.7,
      veg: true,
      parentId: "7861",
      avgRatingString: "4.7",
      totalRatingsString: "10K+",
      sla: {
        deliveryTime: 18,
        lastMileTravel: 1.6,
        serviceability: "SERVICEABLE",
        slaString: "15-20 mins",
        lastMileTravelString: "1.6 km",
        iconType: "ICON_TYPE_EMPTY",
      },
    },
  },
  {
    type: "resturant",
    info: {
      id: "199639",
      name: "Apna Sweets",
      cloudinaryImageId: "kt09zylanc2qd5eg116a",
      locality: "Bhakt Prahlad Nagar",
      areaName: "Bhakt Prahlad Nagar",
      costForTwo: "₹300 for two",
      cuisines: [
        "Sweets",
        "Beverages",
        "Street Food",
        "South Indian",
        "Fast Food",
        "Chinese",
        "Desserts",
      ],
      avgRating: 4.7,
      veg: true,
      parentId: "8960",
      avgRatingString: "4.7",
      totalRatingsString: "10K+",
      sla: {
        deliveryTime: 20,
        lastMileTravel: 1.6,
        serviceability: "SERVICEABLE",
        slaString: "20-25 mins",
        lastMileTravelString: "1.6 km",
        iconType: "ICON_TYPE_EMPTY",
      },
    },
  },
  {
    type: "resturant",
    info: {
      id: "826586",
      name: "Pastas By Pizza Hut",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2024/4/1/e77822ad-4e01-4a38-ae6b-f50cd19352dd_826586.JPG",
      locality: "Phooti Kothi",
      areaName: "Sudama Nagar",
      costForTwo: "₹400 for two",
      cuisines: ["Pastas"],
      avgRating: 3.6,
      parentId: "306806",
      avgRatingString: "3.6",
      totalRatingsString: "10+",
      sla: {
        deliveryTime: 35,
        lastMileTravel: 3.9,
        serviceability: "SERVICEABLE",
        slaString: "35-40 mins",
        lastMileTravelString: "3.9 km",
        iconType: "ICON_TYPE_EMPTY",
      },
    },
  },
  {
    type: "resturant",
    info: {
      id: "581971",
      name: "Pizza Hut",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2024/7/17/93a8ff76-89f2-4ed3-8cb2-43ed8361200f_581971.jpg",
      locality: "Airport Road",
      areaName: "Kalani Nagar",
      costForTwo: "₹350 for two",
      cuisines: ["Pizzas"],
      avgRating: 4.2,
      parentId: "721",
      avgRatingString: "4.2",
      totalRatingsString: "1K+",
      sla: {
        deliveryTime: 20,
        lastMileTravel: 1.5,
        serviceability: "SERVICEABLE",
        slaString: "20-25 mins",
        lastMileTravelString: "1.5 km",
        iconType: "ICON_TYPE_EMPTY",
      },
    },
  },
  {
    type: "resturant",
    info: {
      id: "70800",
      name: "McDonald's",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2024/4/1/fedaee6f-c5e9-4f19-8188-93627e6d6776_70800.JPG",
      locality: "Malhar Mega Mall",
      areaName: "Scheme 54 Pu4",
      costForTwo: "₹400 for two",
      cuisines: ["Burgers", "Beverages", "Cafe", "Desserts"],
      avgRating: 4.4,
      parentId: "630",
      avgRatingString: "4.4",
      totalRatingsString: "5K+",
      sla: {
        deliveryTime: 36,
        lastMileTravel: 8.3,
        serviceability: "SERVICEABLE",
        slaString: "35-40 mins",
        lastMileTravelString: "8.3 km",
        iconType: "ICON_TYPE_EMPTY",
      },
    },
  },
  {
    type: "resturant",
    info: {
      id: "192426",
      name: "McCafe by McDonald's",
      cloudinaryImageId: "wffhtjwplmfoxtg8y4s7",
      locality: "Orange Business Park",
      areaName: "Bhawarkuan Main Road",
      costForTwo: "₹250 for two",
      cuisines: ["American", "Beverages", "Desserts"],
      avgRating: 4.1,
      parentId: "8263",
      avgRatingString: "4.1",
      totalRatingsString: "100+",
      sla: {
        deliveryTime: 32,
        lastMileTravel: 5.6,
        serviceability: "SERVICEABLE",
        slaString: "30-35 mins",
        lastMileTravelString: "5.6 km",
        iconType: "ICON_TYPE_EMPTY",
      },
    },
  },
  {
    type: "resturant",
    info: {
      id: "630711",
      name: "The Belgian Waffle Co.",
      cloudinaryImageId: "5116a385bac0548e06c33c08350fbf11",
      locality: "Sapna Sangeeta",
      areaName: "Khatiwala Tank",
      costForTwo: "₹200 for two",
      cuisines: ["Waffle", "Desserts", "Ice Cream"],
      avgRating: 4.6,
      veg: true,
      parentId: "2233",
      avgRatingString: "4.6",
      totalRatingsString: "1K+",
      sla: {
        deliveryTime: 33,
        lastMileTravel: 5,
        serviceability: "SERVICEABLE",
        slaString: "30-35 mins",
        lastMileTravelString: "5.0 km",
        iconType: "ICON_TYPE_EMPTY",
      },
    },
  },
  {
    type: "resturant",
    info: {
      id: "566282",
      name: "Faasos' Signature Wraps & Rolls",
      cloudinaryImageId: "c583ca6ce40b426797a78ae2ac91f2ec",
      locality: "Raghav Regency",
      areaName: "Sudama Nagar",
      costForTwo: "₹350 for two",
      cuisines: [
        "Fast Food",
        "Snacks",
        "North Indian",
        "Desserts",
        "Beverages",
      ],
      avgRating: 4.1,
      parentId: "340366",
      avgRatingString: "4.1",
      totalRatingsString: "100+",
      sla: {
        deliveryTime: 33,
        lastMileTravel: 4.1,
        serviceability: "SERVICEABLE",
        slaString: "30-35 mins",
        lastMileTravelString: "4.1 km",
        iconType: "ICON_TYPE_EMPTY",
      },
    },
  },
  {
    type: "resturant",
    info: {
      id: "714096",
      name: "Go Zero Ice Creams & Desserts",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2024/4/23/abb8a1dc-ff69-4d04-b0a4-bf01b06b3156_714096.JPG",
      locality: "Raghav Regency",
      areaName: "SUDAMA NAGAR",
      costForTwo: "₹150 for two",
      cuisines: ["Ice Cream", "Desserts", "Healthy Food"],
      avgRating: 4.2,
      veg: true,
      parentId: "343689",
      avgRatingString: "4.2",
      totalRatingsString: "100+",
      sla: {
        deliveryTime: 27,
        lastMileTravel: 4.2,
        serviceability: "SERVICEABLE",
        slaString: "25-30 mins",
        lastMileTravelString: "4.2 km",
        iconType: "ICON_TYPE_EMPTY",
      },
    },
  },
  {
    type: "resturant",
    info: {
      id: "575049",
      name: "Veg Daawat by Behrouz",
      cloudinaryImageId: "2b579171cefc545ce6479e21c0016798",
      locality: "D Sector",
      areaName: "Sudama Nagar",
      costForTwo: "₹700 for two",
      cuisines: [
        "Biryani",
        "North Indian",
        "Kebabs",
        "Mughlai",
        "Beverages",
        "Desserts",
      ],
      avgRating: 4.5,
      veg: true,
      parentId: "344904",
      avgRatingString: "4.5",
      totalRatingsString: "20+",
      sla: {
        deliveryTime: 26,
        lastMileTravel: 4.1,
        serviceability: "SERVICEABLE",
        slaString: "25-30 mins",
        lastMileTravelString: "4.1 km",
        iconType: "ICON_TYPE_EMPTY",
      },
    },
  },
  {
    type: "resturant",
    info: {
      id: "263735",
      name: "Shravan Specials by Lunchbox",
      cloudinaryImageId: "k5rppynokexzna1caaca",
      locality: "Raghav Regency",
      areaName: "Sudama Nagar",
      costForTwo: "₹200 for two",
      cuisines: ["Biryani", "North Indian", "Desserts", "Beverages"],
      avgRating: 4.3,
      parentId: "21938",
      avgRatingString: "4.3",
      totalRatingsString: "100+",
      sla: {
        deliveryTime: 29,
        lastMileTravel: 4.1,
        serviceability: "SERVICEABLE",
        slaString: "25-30 mins",
        lastMileTravelString: "4.1 km",
        iconType: "ICON_TYPE_EMPTY",
      },
    },
  },
  {
    type: "resturant",
    info: {
      id: "801296",
      name: "Makhani Darbar",
      cloudinaryImageId: "c583da4b69d264ffe705e5918fad0e98",
      locality: "Annapoorna FC",
      areaName: "Raghav Regency",
      costForTwo: "₹500 for two",
      cuisines: [
        "Biryani",
        "North Indian",
        "Kebabs",
        "Mughlai",
        "Beverages",
        "Desserts",
      ],
      avgRating: 2.3,
      parentId: "478595",
      avgRatingString: "2.3",
      totalRatingsString: "3",
      sla: {
        deliveryTime: 33,
        lastMileTravel: 4.1,
        serviceability: "SERVICEABLE",
        slaString: "30-35 mins",
        lastMileTravelString: "4.1 km",
        iconType: "ICON_TYPE_EMPTY",
      },
    },
  },

  {
    type: "resturant",
    info: {
      id: "536863",
      name: "La Pino'z Pizza",
      cloudinaryImageId: "5fe4444a065b60c4fe39ef975222c12b",
      locality: "kalani Nagar",
      areaName: "Sarafa",
      costForTwo: "₹400 for two",
      cuisines: ["Pizzas", "Pastas", "Italian", "Desserts", "Beverages"],
      avgRating: 4.1,
      veg: true,
      parentId: "4961",
      avgRatingString: "4.1",
      totalRatingsString: "1K+",
      sla: {
        deliveryTime: 19,
        lastMileTravel: 1.5,
        serviceability: "SERVICEABLE",
        slaString: "15-20 mins",
        lastMileTravelString: "1.5 km",
        iconType: "ICON_TYPE_EMPTY",
      },
    },
  },
  {
    type: "resturant",
    info: {
      id: "156145",
      name: "The Good Bowl",
      cloudinaryImageId: "6e04be27387483a7c00444f8e8241108",
      locality: "Annapoorna FC",
      areaName: "Sudama Nagar",
      costForTwo: "₹400 for two",
      cuisines: [
        "Biryani",
        "North Indian",
        "Pastas",
        "Punjabi",
        "Desserts",
        "Beverages",
      ],
      avgRating: 4.2,
      parentId: "7918",
      avgRatingString: "4.2",
      totalRatingsString: "1K+",
      sla: {
        deliveryTime: 29,
        lastMileTravel: 4.1,
        serviceability: "SERVICEABLE",
        slaString: "25-30 mins",
        lastMileTravelString: "4.1 km",
        iconType: "ICON_TYPE_EMPTY",
      },
    },
  },
  {
    type: "resturant",
    info: {
      id: "770309",
      name: "Keventers - Milkshakes & Desserts",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2024/6/20/5c0cf9a2-1195-4825-956b-bf00c6660d91_770309.JPG",
      locality: "Sapna Sangeeta Road",
      areaName: "Narendra Chamber",
      costForTwo: "₹300 for two",
      cuisines: ["Beverages", "Ice Cream", "Desserts", "Healthy Food"],
      avgRating: 4.5,
      veg: true,
      parentId: "268997",
      avgRatingString: "4.5",
      totalRatingsString: "100+",
      sla: {
        deliveryTime: 28,
        lastMileTravel: 5,
        serviceability: "SERVICEABLE",
        slaString: "25-30 mins",
        lastMileTravelString: "5.0 km",
        iconType: "ICON_TYPE_EMPTY",
      },
    },
  },
  {
    type: "resturant",
    info: {
      id: "80652",
      name: "Firangi Bake",
      cloudinaryImageId: "v9qsbs5qxvtq8jln33sw",
      locality: "Raghav Regency",
      areaName: "Sudama Nagar",
      costForTwo: "₹400 for two",
      cuisines: [
        "Pizzas",
        "Pastas",
        "Italian",
        "Mexican",
        "Healthy Food",
        "Desserts",
        "Beverages",
      ],
      avgRating: 4.3,
      parentId: "3952",
      avgRatingString: "4.3",
      totalRatingsString: "500+",
      sla: {
        deliveryTime: 31,
        lastMileTravel: 4.1,
        serviceability: "SERVICEABLE",
        slaString: "30-35 mins",
        lastMileTravelString: "4.1 km",
        iconType: "ICON_TYPE_EMPTY",
      },
    },
  },
  {
    type: "resturant",
    info: {
      id: "80653",
      name: "Sweet Truth - Cake and Desserts",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2024/7/2/eb5eafc7-0a8d-4d7c-93d6-388084641096_80653.JPG",
      locality: "Raghav Regency",
      areaName: "Sudama Nagar",
      costForTwo: "₹450 for two",
      cuisines: ["Snacks", "Bakery", "Desserts", "Beverages"],
      avgRating: 4.4,
      parentId: "4444",
      avgRatingString: "4.4",
      totalRatingsString: "1K+",
      sla: {
        deliveryTime: 22,
        lastMileTravel: 4.1,
        serviceability: "SERVICEABLE",
        slaString: "20-25 mins",
        lastMileTravelString: "4.1 km",
        iconType: "ICON_TYPE_EMPTY",
      },
    },
  },
];

export const IMG_CDN =
  "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/";
export const FETCH_URL =
  "https://www.swiggy.com/dapi/menu/pl?page-type=REGULAR_MENU&complete-menu=true&lat=22.71700&lng=75.83370&restaurantId=";
